title: Jesus Arroyo
email: me@jesusarroyo.com
baseurl: ""
url: "https://jesusarroyo.com"
twitter_username: jesusharroyo
github_username: jesusha123
linkedin_username: jesusha

# Build settings
theme: minima
plugins:
  - jekyll-feed
